#!/bin/bash

echo "📝 Para executar manualmente o Emergency Build Fix:"
echo ""
echo "1. Abre o browser e vai para:"
echo "   https://github.com/aapais/mainframe-ai-assistant/actions/workflows/emergency-fix.yml"
echo ""
echo "2. Clica no botão 'Run workflow' no canto superior direito"
echo ""
echo "3. Seleciona:"
echo "   - Branch: master"
echo "   - Fix type: all"
echo ""
echo "4. Clica no botão verde 'Run workflow'"
echo ""
echo "5. Aguarda ~2-3 minutos para completar"
echo ""
echo "OU executar via GitHub CLI (se autenticado):"
echo "gh workflow run emergency-fix.yml --repo aapais/mainframe-ai-assistant -f fix_type=all"
echo ""
echo "🔗 Link direto:"
echo "https://github.com/aapais/mainframe-ai-assistant/actions/workflows/emergency-fix.yml"